### ISSUE TITLE
Advanced Missile Guidance, AT Titan Vs AirUnits

### ISSUE THREAD

**Issue by hanibalv2** [saildeep/SmmCaptureEvolve.Altis#1]
Countermeasures not work, no CPA Alarm in vehicle, AI dont use Titan against anything

idea :  deactivate Advanced Missile Guidance till ACE3 fixed the bug

**Comment by hanibalv2** [comment]
close the issue wont fix the issue

**Comment by saildeep** [comment]
It's nothing we can fix, we may disable ai air units, as they are to strong imho

**Comment by hanibalv2** [comment]
af8e7356f34b028966c67d2e09a7beac8d61626a 

i let the AMG activ in the ace.settings, becuase i cant determin if the systems is used by another weapon then the launchers. (maybe helicopters?) 

so i kick out the javelin launchers.

i set a hit in the param.hpp. (just a idea.)
