### ISSUE TITLE
ace vs (rhs / "niarms" / vanilla)

### ISSUE THREAD

**Issue by hanibalv2** [saildeep/SmmCaptureEvolve.Altis#10]
There seems to be compatibility problems between ace and rhs/vanilla.
The target tracking function in attack helicopters and tanks wont work from time to time (ace/rhs problem). 

There is also a problem with the "Fire Control System" in vehicles (ace feature). This is now a vanilla function and ace deactivate it maybe with the last patch (?) but it seems rhs also has a function like this activated -> problems. 
 
like #1 we should determine these features and deactivate them for a better gameplay.

**Comment by saildeep** [comment]
Is the ace/this update for Jets DLC compability already released?

**Comment by saildeep** [comment]
As we are now moving back to vanilla + ace +tfar i consider this closed
