### ISSUE TITLE
non thermal vs. launcher

### ISSUE THREAD

**Issue by justcallmeduncan** [saildeep/SmmCaptureEvolve.Altis#11]
some launcher (static) may not work without thermal view

**Comment by saildeep** [comment]
Intended feature of ace https://ace3mod.com/wiki/feature/missileguidance.html

**Comment by justcallmeduncan** [comment]
so they need to be removed or there must be a way to active thermal for those

**Comment by saildeep** [comment]
I just understood the problem with this. I think removing them would be better.

**Comment by hanibalv2** [comment]
attack helicopter becomes very expensive now. So we can reuse the thermal scope again.
