### ISSUE TITLE
Buy a triggered zone

### ISSUE THREAD

**Issue by hanibalv2** [saildeep/SmmCaptureEvolve.Altis#12]
As in #7 descripted i work on a function so you can buy a triggerd zone for a fair price.

The current status :
1. You cann only buy a Zone if 80 Percent of al Units + Vehicles in the zone are neutralized.
2. The Price is than determined by ( remaining Units *1000  + remaining Vehicles* 10000 ) / time.
3. The result plot look like a log(1/x) function.

**Comment by hanibalv2** [comment]
This will help the players to continue game progress and dont need to search for stuck units.

**Comment by saildeep** [comment]
no longer needed due to new spawner system
