### ISSUE TITLE
Mortar ammo

### ISSUE THREAD

**Issue by hanibalv2** [saildeep/SmmCaptureEvolve.Altis#27]
There is no ammo for the mortar under ace

**Comment by saildeep** [comment]
Please add the following ammo types if ace is `present:`

- ACE_1Rnd_82mm_Mo_HE
- ACE_1Rnd_82mm_Mo_Smoke
- ACE_1Rnd_82mm_Mo_Illum
- ACE_1Rnd_82mm_Mo_HE_Guided
- ACE_1Rnd_82mm_Mo_HE_LaserGuided

**Comment by hanibalv2** [comment]
The shells cannot be added to the arsenal, as they cannot be assigned to the magazine group.

**Comment by hanibalv2** [comment]
The morta can be rearmed via the ammo hemmet, but the sheels cant be shoot. Maybe a bug
