### ISSUE TITLE
drone balance

### ISSUE THREAD

**Issue by hanibalv2** [saildeep/SmmCaptureEvolve.Altis#35]
UAV Drones (the planes) are very overpowered.

Suggestion:

Remove weapons and use them as a reconnaissance aircraft.

**Comment by saildeep** [comment]
If we sell ammo for them, i don't see any option to have an unarmed one. Despite this there still exist backpack-uavs.

**Comment by saildeep** [comment]
As we introduced the dynamic vehicle loadout i consider this closed.
