### ISSUE TITLE
switch class

### ISSUE THREAD

**Issue by hanibalv2** [saildeep/SmmCaptureEvolve.Altis#37]
I think a "change soldier class" function would be relatively useful.
 So you don't have to kill yourself first via the menu and then join the game again as a new soldier.

**Comment by saildeep** [comment]
The idea for using slots was to prevent the player from becoming the ultimate super soldier and getting used to playing on role for maybe multiple session and improving on it. Therefore i think this hurdle is a appropriate method to stop players from always switching to the class with "the coolest gun". Also the number of slots per class are limited ATM, which i think is very useful, to prevent to many snipers e.g.
