### ISSUE TITLE
Gunbag/mine detector(sidearm) missing

### ISSUE THREAD

**Issue by justcallmeduncan** [saildeep/SmmCaptureEvolve.Altis#4]
Gunbag is a purchasable backpack in shop, but cant be use in game

**Comment by hanibalv2** [comment]
ace items are complete disabled and will be added item per item manually in game

**Comment by hanibalv2** [comment]
mine detector(sidearm) also missing

**Comment by justcallmeduncan** [comment]
Removed ACE Gunbags and added the mine detectors

**Comment by hanibalv2** [comment]
only one ACE mine detector appears. 
maybe it is :"ACE_VHM**2**"  insteats of  "ACE_VHM**3**" ? in  5bd05b390dac1332b9cb5f1e36a77fd8114e242a
