### ISSUE TITLE
Vehicles do not patrol

### ISSUE THREAD

**Issue by hanibalv2** [saildeep/SmmCaptureEvolve.Altis#42]
I think there is a problem between the loopVehicle script and loopUnit script that cause an error for the whole vehicle. 
In the master branch the loopUnit script was not added to vehicle crew.

**Comment by saildeep** [comment]
As of yesterday some vehicles were patrolling. Can we consider this closed?

**Comment by hanibalv2** [comment]
They weren't patrolling, they were looking for the enemy.
nevertheless I have solved the problem now
