### ISSUE TITLE
Zeus / Ai control

### ISSUE THREAD

**Issue by hanibalv2** [saildeep/SmmCaptureEvolve.Altis#44]
Can someone have a look at:

https://steamcommunity.com/sharedfiles/filedetails/?id=491016790

it seems to be very intuitive and is ace compatible.

**Comment by saildeep** [comment]
I tried before and it doesn't always work. For this to work, the AI needs to be commanded by the player, which will create additional problems (e.g. locality change). Also, I do not see Zeus compatibility.  Therefore this won't be useful for us. I also aim for keeping external dependencies to a minimum. @hanibalv2  please use more descriptive titles for your issues ;)
