### ISSUE TITLE
improve unit spawn

### ISSUE THREAD

**Issue by hanibalv2** [saildeep/SmmCaptureEvolve.Altis#6]
as described at : https://community.bistudio.com/wiki/Position#PositionASL

we coud maby detect surface object like trees and rock by using the correct getPos funkction

also **getPosWorld** should be forced to used. It is the fastes function.
https://community.bistudio.com/wiki/Code_Optimisation

**Comment by saildeep** [comment]
We should implement a fallback, in case our current solution does not find any safe spot

**Comment by hanibalv2** [comment]
fallback implemented. But it is not satisfactory in my opinion.

**Comment by justcallmeduncan** [comment]
-units still spawn in rocks

**Comment by hanibalv2** [comment]
unit spawn optimize -> 94f3f8ea13126b81ede3a3312ff969ca455a9d06 

but some units still spawn in the origin of the map.

I try to fix this via :
```sqf
if( (_unit distance [0,0]) < 100)then{
diag_log (format ["Unit %1 spawn in origin of the map, setDamage 1",_x]);
_unit setDamage 1;
};
```

in on_zone_enter 60-65, but i can not trigger this. Maybe the code is faster execute than the unit spawn.

**Comment by hanibalv2** [comment]
Visual test result: As i see on our server(15.06.2017-01:42:00) Units can still spawn in rock.
Maybe 20 Percent possiblitiy 

It seems that they spawn on a nother rock wich is still inside another rock.

**Comment by saildeep** [comment]
New spawning system, tries to spawn units in nearby buildings and only uses the old method as a fallback. Moreover it is sufficient to hold the position at the zone center to conquer it. Therefore this is no longer relevant.
