### ISSUE TITLE
Add AI RHS Units

### ISSUE THREAD

**Issue by saildeep** [saildeep/SmmCaptureEvolve.Altis#8]
We need to add more AI-purchasable Units and Vehicles for the RHS-Mod. This includes Anti-Air, Anti-Vehicle, Machine Gun, DMR units and more light Vehicles and tanks. We may consider removing the helicopters

**Comment by justcallmeduncan** [comment]
``	[ 
		["rhs_msv_rifleman",10], ["rhs_msv_grenadier",15], ["rhs_msv_machinegunner",20],
		["rhs_msv_at",25],["rhs_msv_marksman",20], ["rhs_msv_sergeant",10],
		["rhs_msv_aa",25], ["rhs_msv_medic",10], ["rhs_vmf_recon_marksman",20], 
		["rhs_msv_combatcrew",10]
		
		 
	],
		
	[ 
		["rhsusf_army_ocp_rifleman_m4",10], ["rhsusf_army_ocp_grenadier",15], ["rhsusf_army_ocp_machinegunner",20],
		["rhsusf_army_ocp_javelin",25], ["rhsusf_army_ocp_marksman",20],["rhsusf_army_ocp_squadleader",10], 
		["rhsusf_army_ocp_aa",25],["rhsusf_army_ocp_medic",10],["rhsusf_army_ocp_sniper",20], 
		["rhsusf_army_ocp_combatcrewman",10]
		
	],

	[  
		["rhssaf_army_m10_para_rifleman_hk416",10],["rhssaf_army_m10_para_gl_m320",15],["rhssaf_army_m10_para_mgun_m84",20],
		["rhssaf_army_m10_para_spec_at",25],["rhssaf_army_m10_para_sniper_m76",20],["rhssaf_army_m10_para_sq_lead",10],
		["rhssaf_army_m10_para_spec_aa",25],["rhssaf_army_m10_para_medic",10],["rhssaf_army_m10_para_sniper_m82a1",20],
		["rhssaf_army_m10_para_officer",10]
	]

			];

**Comment by justcallmeduncan** [comment]
-well theres is a anti air vehicle in each faction.
-static machin gun?
-DMR units are purchasable

**Comment by saildeep** [comment]
e.g. different Uniforms....

**Comment by justcallmeduncan** [comment]
Added for Bluefor and opfor
