### ISSUE TITLE
Transferable money

### ISSUE THREAD

**Issue by justcallmeduncan** [saildeep/SmmCaptureEvolve.Altis#9]
we need tradable money

**Comment by saildeep** [comment]
The player should be able to send an other player a fixed amount of money by using the common interaction addAction method

**Comment by saildeep** [comment]
The best option would be to open a Dialog on interaction, where the player can adjust the amount with a slider. Are there any other ideas?

**Comment by justcallmeduncan** [comment]
i think we need only some fix amounts like 50,500 and 2000$
